"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertCircle, Landmark, Loader2 } from "lucide-react";
import appClient from "@/lib/appClient";

type BondInvestment = {
    _id: string; investmentId: string; amountUsd: number; maturityDate: string; status: string;
    bondSnapshot: { name?: string; code?: string; couponRateAnnual?: number };
    paidFromWallet?: { currency?: string; amount?: number };
};
type Response = { investments?: BondInvestment[]; summary?: { totalInvestedUsd: number; activeInvestmentCount: number; activeInvestedUsd: number }; pagination?: { total: number; page: number; totalPages: number; limit: number } };
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const date = (value: string) => new Date(value).toLocaleDateString("en-US", { day: "numeric", month: "short", year: "numeric" });
const statusClass: Record<string, string> = { active: "bg-emerald-500/15 text-emerald-400 border-emerald-500/20", matured: "bg-blue-500/15 text-blue-400 border-blue-500/20", closed: "bg-slate-500/15 text-slate-400 border-slate-500/20", cancelled: "bg-rose-500/15 text-rose-400 border-rose-500/20" };
const statuses = [{ label: "All Status", value: "" }, { label: "Active", value: "active" }, { label: "Matured", value: "matured" }, { label: "Closed", value: "closed" }];

export default function MyBondInvestments() {
    const searchParams = useSearchParams(); const router = useRouter();
    const status = searchParams.get("status") ?? ""; const page = Number(searchParams.get("page") ?? "1");
    const [items, setItems] = useState<BondInvestment[]>([]); const [summary, setSummary] = useState<Response["summary"]>();
    const [pagination, setPagination] = useState({ total: 0, page: 1, totalPages: 1, limit: 9 }); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
    const updateUrl = (nextStatus: string, nextPage: number) => { const params = new URLSearchParams(); if (nextStatus) params.set("status", nextStatus); if (nextPage > 1) params.set("page", String(nextPage)); router.replace(`?${params}`, { scroll: false }); };
    useEffect(() => { let cancelled = false; void (async () => { setLoading(true); setError(""); try { const response = await appClient.get("/api/bonds/investments/my", { params: { status: status || undefined, page, limit: 9 } }); const data = response.data as Response; if (cancelled) return; setItems(data.investments ?? []); setSummary(data.summary); setPagination(data.pagination ?? { total: 0, page, totalPages: 1, limit: 9 }); } catch { if (!cancelled) setError("Could not load your bond investments. Please try again."); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, [page, status]);

    return <div className="min-h-screen bg-[#EEF3FB]"><section className="bg-[#0B1628]"><div className="mx-auto max-w-6xl px-6 py-10 sm:px-8"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/10"><Landmark className="h-5 w-5 text-white" /></span><div><h1 className="text-[18px] font-bold text-white">My Bonds</h1><p className="mt-1 text-[12px] text-white/55">Your fixed-income investments and maturity schedule</p></div></div>{summary && <div className="mt-8 grid grid-cols-2 gap-x-8 gap-y-6 sm:grid-cols-3"><Stat label="Total invested" value={money(summary.totalInvestedUsd)} /><Stat label="Active bonds" value={String(summary.activeInvestmentCount)} /><Stat label="Active value" value={money(summary.activeInvestedUsd)} /></div>}</div></section><main className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><div className="mb-6 flex flex-wrap items-center gap-2">{statuses.map(filter => <button key={filter.value} onClick={() => updateUrl(filter.value, 1)} className={`h-8 rounded-full px-4 text-[12.5px] font-semibold transition ${status === filter.value ? "bg-[#0B2E84] text-white shadow-sm" : "border border-[#E2E8F0] bg-white text-slate-600 hover:border-[#0B2E84]/30"}`}>{filter.label}</button>)}</div>{error && <div className="mb-6 flex items-center gap-3 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-[13px] text-rose-700"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div>}{loading ? <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-[#0B2E84]" /></div> : items.length ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{items.map(item => <BondCard key={item._id} item={item} />)}</div> : <Empty filtered={!!status} />}{pagination.totalPages > 1 && <div className="mt-8 flex justify-center gap-2">{Array.from({ length: pagination.totalPages }, (_, index) => index + 1).map(number => <button key={number} onClick={() => updateUrl(status, number)} className={`h-9 w-9 rounded-xl text-[13px] font-semibold ${page === number ? "bg-[#0B2E84] text-white" : "border border-[#E2E8F0] bg-white text-slate-600"}`}>{number}</button>)}</div>}</main></div>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div><p className="text-[11px] font-bold uppercase tracking-[0.09em] text-white/40">{label}</p><p className="mt-1 text-[22px] font-bold leading-none text-white">{value}</p></div>; }
function BondCard({ item }: { item: BondInvestment }) { const bond = item.bondSnapshot ?? {}; return <Link href={`/my-bonds/${item._id}`} className="group flex flex-col gap-4 rounded-2xl border border-[#E2E8F0] bg-white p-5 shadow-sm transition hover:border-[#0B2E84]/25 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#EFF4FF]"><Landmark className="h-5 w-5 text-[#0B2E84]" /></span><div><p className="text-[13.5px] font-bold leading-tight text-[#0F172A]">{bond.name || "Bond investment"}</p><p className="mt-0.5 text-[11.5px] text-slate-500">{bond.code || "Fixed income"}</p></div></div><span className={`rounded-full border px-2.5 py-0.5 text-[10.5px] font-bold uppercase tracking-wide ${statusClass[item.status] || statusClass.active}`}>{item.status}</span></div><div className="grid grid-cols-3 gap-3"><Info label="Invested" value={money(item.amountUsd)} /><Info label="Coupon" value={`${Number(bond.couponRateAnnual || 0).toFixed(2)}%`} green /><Info label="Maturity" value={date(item.maturityDate)} /></div><div className="flex items-center justify-between border-t border-[#F1F5F9] pt-3"><p className="font-mono text-[11px] text-slate-400">{item.investmentId}</p><p className="text-[11px] font-medium text-[#0B2E84] group-hover:underline">View details</p></div></Link>; }
function Info({ label, value, green }: { label: string; value: string; green?: boolean }) { return <div className="rounded-xl bg-[#F8FAFC] px-3 py-2.5"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-1 text-[13px] font-bold ${green ? "text-emerald-600" : "text-[#0F172A]"}`}>{value}</p></div>; }
function Empty({ filtered }: { filtered: boolean }) { return <div className="flex flex-col items-center py-20 text-center"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#EFF4FF]"><Landmark className="h-8 w-8 text-[#0B2E84]" /></span><h2 className="mt-5 text-[16px] font-bold text-[#0F172A]">{filtered ? "No bond investments match" : "No bond investments yet"}</h2><p className="mt-2 max-w-xs text-[13px] leading-6 text-slate-500">{filtered ? "Try a different status to see your investments." : "Explore available bonds to add fixed-income investments to your portfolio."}</p>{!filtered && <Link href="/bonds" className="mt-5 rounded-xl bg-[#0B2E84] px-5 py-2.5 text-[13px] font-bold text-white hover:bg-[#082461]">Explore Bonds</Link>}</div>; }
