"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Landmark, Loader2, ShieldCheck } from "lucide-react";

type Bond = { _id: string; name: string; code: string; shortDescription?: string; couponRateAnnual: number; couponFrequency: string; termMonths: number; minInvestment: number; riskLevel: string };
const money = (amount: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(amount);
const title = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, char => char.toUpperCase());
const term = (months: number) => months % 12 === 0 ? `${months / 12} year${months === 12 ? "" : "s"}` : `${months} months`;

export default function PublicBondOfferings() {
    const [bonds, setBonds] = useState<Bond[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
    useEffect(() => { let cancelled = false; void (async () => { try { const response = await fetch("/api/public/bonds?limit=24"); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || "Could not load bond offerings."); if (!cancelled) setBonds(payload.bonds?.docs ?? []); } catch (err) { if (!cancelled) setError(err instanceof Error ? err.message : "Could not load bond offerings."); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, []);
    return <main className="min-h-screen bg-[#F7F9FD] pt-24 md:pt-32"><section className="border-b border-[#DCE6F7] bg-[radial-gradient(circle_at_85%_10%,rgba(42,96,220,.16),transparent_28%),linear-gradient(135deg,#F7FAFF_0%,#EAF1FF_100%)]"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8 lg:py-20"><div className="max-w-3xl"><p className="inline-flex items-center gap-2 rounded-full border border-[#BFD3FF] bg-white/70 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.14em] text-[#0B3D91]"><Landmark className="h-3.5 w-3.5" /> Fixed-income opportunities</p><h1 className="mt-5 font-serif text-4xl font-semibold leading-tight text-[#071F55] sm:text-5xl">Build stability into your investment strategy.</h1><p className="mt-5 max-w-2xl text-base leading-8 text-[#405577]">Explore active Merlion bond offerings with defined coupon rates, transparent terms, and clear maturity schedules.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><Feature label="Defined income" body="View the annual coupon and payment frequency before you invest." /><Feature label="Transparent terms" body="Understand the term, minimum amount, risk level, and documentation." /><Feature label="Secure onboarding" body="Sign in and complete verification before making an investment." /></div></div></section><section className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-[#2563EB]">Available offerings</p><h2 className="mt-2 text-2xl font-bold text-[#071F55]">Explore Bonds</h2></div><Link href="/login" className="inline-flex items-center gap-2 rounded-xl bg-[#071F55] px-4 py-2.5 text-sm font-bold text-white transition hover:bg-[#0B3D91]">Login to invest <ArrowRight className="h-4 w-4" /></Link></div>{loading ? <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-[#0B3D91]" /></div> : error ? <div className="mt-8 rounded-2xl border border-rose-200 bg-white p-8 text-center text-sm text-rose-700">{error}</div> : bonds.length ? <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{bonds.map(bond => <BondCard key={bond._id} bond={bond} />)}</div> : <div className="mt-8 rounded-2xl border border-dashed border-[#C9D7EE] bg-white px-6 py-16 text-center"><Landmark className="mx-auto h-8 w-8 text-[#0B3D91]" /><h2 className="mt-4 text-lg font-bold text-[#071F55]">New bond offerings coming soon</h2><p className="mt-2 text-sm text-slate-500">Please check back for active fixed-income opportunities.</p></div>}</section></main>;
}

function BondCard({ bond }: { bond: Bond }) { return <article className="flex min-h-[320px] flex-col rounded-2xl border border-[#D7E0F1] bg-white p-6 shadow-[0_18px_45px_rgba(11,35,74,.06)] transition hover:-translate-y-1 hover:shadow-[0_28px_70px_rgba(11,35,74,.12)]"><div className="flex items-start justify-between gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#073889] text-white"><Landmark className="h-5 w-5" /></span><span className="rounded-lg bg-blue-50 px-3 py-1.5 text-xs font-bold text-[#0B3D91]">{title(bond.riskLevel)} risk</span></div><h3 className="mt-6 text-xl font-bold text-[#071F55]">{bond.name}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-[#405577]">{bond.shortDescription || "A fixed-income offering built for disciplined, long-term investors."}</p><dl className="mt-6 grid grid-cols-2 gap-3 border-y border-slate-100 py-4"><Metric label="Annual coupon" value={`${Number(bond.couponRateAnnual).toFixed(2)}%`} /><Metric label="Term" value={term(bond.termMonths)} /><Metric label="Frequency" value={title(bond.couponFrequency)} /><Metric label="Minimum" value={money(bond.minInvestment)} /></dl><Link href="/login" className="mt-auto inline-flex items-center justify-center gap-2 rounded-xl border border-[#0B3D91] py-3 text-sm font-bold text-[#071F55] transition hover:bg-[#071F55] hover:text-white">View investment access <ArrowRight className="h-4 w-4" /></Link></article>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 text-[13px] font-bold text-[#071F55]">{value}</dd></div>; }
function Feature({ label, body }: { label: string; body: string }) { return <div className="rounded-2xl border border-white/80 bg-white/65 p-4"><ShieldCheck className="h-4 w-4 text-[#0B3D91]" /><p className="mt-3 text-sm font-bold text-[#071F55]">{label}</p><p className="mt-1 text-xs leading-5 text-[#405577]">{body}</p></div>; }
