"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, FileCheck2, Landmark, Loader2, Percent, Shield, WalletCards } from "lucide-react";

type Bond = { _id: string; name: string; code: string; shortDescription?: string; couponRateAnnual: number; couponFrequency: string; termMonths: number; minInvestment: number; riskLevel: string };
const money = (amount: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(amount);
const title = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, char => char.toUpperCase());
const term = (months: number) => months % 12 === 0 ? `${months / 12} year${months === 12 ? "" : "s"}` : `${months} months`;

export default function PublicBondOfferingsPage() {
    const [bonds, setBonds] = useState<Bond[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
    useEffect(() => { let cancelled = false; void (async () => { try { const response = await fetch("/api/public/bonds?limit=24"); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || "Could not load bond offerings."); if (!cancelled) setBonds(payload.bonds?.docs ?? []); } catch (err) { if (!cancelled) setError(err instanceof Error ? err.message : "Could not load bond offerings."); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, []);

    return <main className="min-h-screen bg-white text-[#071F55] antialiased">
        <section className="relative min-h-[620px] overflow-hidden bg-[#dcecff] px-4 pt-28 sm:px-6 lg:px-8" style={{ backgroundImage: "linear-gradient(90deg, rgba(255,255,255,.97) 0%, rgba(255,255,255,.78) 36%, rgba(255,255,255,.10) 72%), linear-gradient(180deg, rgba(7,31,85,.48) 0%, rgba(7,31,85,.06) 46%, rgba(255,255,255,.20) 100%), url('/bond-offerings-hero.png')", backgroundSize: "cover", backgroundPosition: "center right" }}>
            <div className="mx-auto max-w-7xl pb-28 pt-16 lg:pb-36 lg:pt-20"><div className="max-w-xl"><p className="mb-7 flex items-center gap-3 text-[12px] font-extrabold uppercase tracking-[0.22em] text-[#0B3D91]"><span className="h-px w-8 bg-[#0B3D91]" /> Our Bonds</p><h1 className="text-5xl font-bold leading-[1.08] tracking-tight text-[#071F55] sm:text-6xl">Fixed Income.<br />Built for Stability.</h1><p className="mt-7 max-w-lg text-base leading-8 text-[#071F55]">Explore active Merlion bond offerings with defined coupon rates, transparent terms, and clear maturity schedules.</p><Link href="#bond-offerings" className="mt-8 inline-flex items-center gap-3 rounded-lg bg-[#083B93] px-7 py-4 text-sm font-bold text-white shadow-[0_14px_26px_rgba(8,59,147,.22)] transition hover:bg-[#071F55]">Explore Bond Offerings <ArrowRight className="h-4 w-4" /></Link></div></div>
        </section>
        <section className="relative z-10 -mt-14 px-4 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-2xl border border-[#d7e0f1] bg-white/95 shadow-[0_22px_60px_rgba(11,35,74,.12)] backdrop-blur md:grid-cols-2 lg:grid-cols-4"><Trust icon={<Percent className="h-8 w-8" />} title="Defined Coupons" body="Review annual coupon rates and payment frequency upfront." /><Trust icon={<CalendarIcon />} title="Clear Maturity" body="Understand the investment term and planned maturity date." /><Trust icon={<Shield className="h-8 w-8" />} title="Risk Transparency" body="Review the risk level and applicable exit terms." /><Trust icon={<FileCheck2 className="h-8 w-8" />} title="Offering Documents" body="Access the official materials after secure sign-in." last /></div></section>
        <section id="bond-offerings" className="px-4 pb-16 pt-12 sm:px-6 lg:px-8 lg:pt-16"><div className="mx-auto max-w-7xl text-center"><h2 className="text-4xl font-bold leading-tight text-[#071F55]">Our Bond Offerings</h2><div className="mx-auto mt-3 h-0.5 w-16 rounded-full bg-[#0B3D91]" /><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-[#071F55]/78">Explore fixed-income opportunities that combine defined income potential with transparent terms.</p>{loading ? <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-[#0B3D91]" /></div> : error ? <div className="mt-8 rounded-2xl border border-rose-200 bg-white p-8 text-sm text-rose-700">{error}</div> : bonds.length ? <div className="mt-10 grid gap-5 text-left md:grid-cols-2 xl:grid-cols-3">{bonds.map(bond => <BondCard key={bond._id} bond={bond} />)}</div> : <div className="mt-8 rounded-2xl border border-dashed border-[#C9D7EE] bg-white px-6 py-16"><Landmark className="mx-auto h-8 w-8 text-[#0B3D91]" /><h2 className="mt-4 text-lg font-bold text-[#071F55]">New bond offerings coming soon</h2><p className="mt-2 text-sm text-slate-500">Please check back for active fixed-income opportunities.</p></div>}</div></section>
    </main>;
}

function Trust({ icon, title, body, last = false }: { icon: React.ReactNode; title: string; body: string; last?: boolean }) { return <div className={`flex items-center gap-5 px-5 py-6 ${last ? "" : "lg:border-r lg:border-[#dbe4f2]"}`}><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-full bg-[#f1f5fc] text-[#0B3D91]">{icon}</div><div><p className="text-base font-bold leading-snug text-[#071F55]">{title}</p><p className="mt-2 text-xs leading-5 text-[#071F55]/75">{body}</p></div></div>; }
function BondCard({ bond }: { bond: Bond }) { return <article className="flex min-h-[320px] flex-col rounded-2xl border border-[#d7e0f1] bg-white p-6 shadow-[0_18px_45px_rgba(11,35,74,.06)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_28px_70px_rgba(11,35,74,.12)]"><div className="flex items-start justify-between gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-xl bg-[#073889] text-white shadow-[0_10px_22px_rgba(7,56,137,.18)]"><Landmark className="h-6 w-6" /></span><span className="inline-flex items-center rounded-lg bg-blue-50 px-3 py-1.5 text-xs font-bold text-[#0B3D91]">{title(bond.riskLevel)} risk</span></div><h3 className="mt-7 text-xl font-bold leading-tight text-[#071F55]">{bond.name}</h3><p className="mt-4 line-clamp-3 text-sm leading-7 text-[#071F55]/78">{bond.shortDescription || "A fixed-income offering built for disciplined, long-term investors."}</p><dl className="mt-8 space-y-3 text-sm"><Metric label="Minimum investment" value={money(bond.minInvestment)} /><Metric label="Annual coupon" value={`${Number(bond.couponRateAnnual).toFixed(2)}%`} /><Metric label="Investment term" value={term(bond.termMonths)} /></dl><Link href="/login" className="mt-auto flex h-12 w-full items-center justify-center gap-3 rounded-lg border border-[#0B3D91] text-sm font-bold text-[#071F55] transition hover:bg-[#071F55] hover:text-white">View Investment Access <ArrowRight className="h-4 w-4" /></Link></article>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4"><span className="text-[#071F55]/70">{label}</span><span className="text-right font-bold text-[#071F55]">{value}</span></div>; }
function CalendarIcon() { return <WalletCards className="h-8 w-8" />; }
